export { api, createCityApi } from "@/lib/api/client";
export { fetchAvailableCities, type AvailableCity } from "@/lib/api/cities";
export { listCatalogCities, type CatalogCity } from "@/lib/api/catalog-cities";
export { listGrades, listEducationStages } from "@/lib/api/grades";
export { getApiErrorMessage } from "@/lib/api/errors";
export {
  listSchools,
  listClassesBySchool,
  listStudentsByClass,
  listStudentsBySchool,
  getStudent,
  type School,
  type SchoolClass,
  type Student,
} from "@/lib/api/students";
export {
  afirmeReadingApi,
  listWordLists,
  getWordList,
  createWordList,
  updateWordList,
  deleteWordList,
  listReadingTexts,
  getReadingText,
  createReadingText,
  updateReadingText,
  deleteReadingText,
  createReadingQuestion,
  createReadingQuestionsBulk,
  updateReadingQuestion,
  deleteReadingQuestion,
  createGuidedSession,
  listGuidedSessions,
  getGuidedSession,
  uploadGuidedSessionAudio,
  deleteGuidedSession,
  toProxiedAudioUrl,
  fetchGuidedAudioObjectUrl,
  resolveGuidedSessionAudioUrl,
} from "@/lib/api/afirme-reading";
export type {
  WordList,
  WordListKind,
  ScopeType,
  DifficultyLevel,
  CreateWordListPayload,
  UpdateWordListPayload,
  ListWordListsParams,
  ReadingText,
  ReadingQuestion,
  GradeRef,
  CreateReadingTextPayload,
  CreateReadingTextQuestionPayload,
  CreateReadingQuestionPayload,
  UpdateReadingQuestionPayload,
  UpdateReadingTextPayload,
  ListReadingTextsParams,
  Grade,
  EducationStage,
  GuidedSession,
  GuidedSessionAnswer,
  CreateGuidedSessionPayload,
  ListGuidedSessionsParams,
  ApiErrorBody,
} from "@/lib/api/afirme-reading";
