export { afirmeReadingApi } from "@/lib/api/afirme-reading/client";
export {
  listWordLists,
  getWordList,
  createWordList,
  updateWordList,
  deleteWordList,
} from "@/lib/api/afirme-reading/word-lists";
export {
  listReadingTexts,
  getReadingText,
  createReadingText,
  updateReadingText,
  deleteReadingText,
} from "@/lib/api/afirme-reading/texts";
export {
  createGuidedSession,
  listGuidedSessions,
  getGuidedSession,
  uploadGuidedSessionAudio,
  deleteGuidedSession,
  toProxiedAudioUrl,
  fetchGuidedAudioObjectUrl,
  resolveGuidedSessionAudioUrl,
} from "@/lib/api/afirme-reading/guided-sessions";
export {
  listEvaluations,
  getEvaluation,
  listReadingSessions,
} from "@/lib/api/afirme-reading/evaluations";
export {
  startReadingSession,
  saveFluency,
  saveComprehensionAnswers,
  getReport,
  submitSession,
} from "@/lib/api/afirme-reading/sessions";
export type {
  WordList,
  WordListKind,
  ScopeType,
  DifficultyLevel,
  CreateWordListPayload,
  UpdateWordListPayload,
  ListWordListsParams,
  ReadingText,
  ReadingQuestion,
  GradeRef,
  CreateReadingTextPayload,
  UpdateReadingTextPayload,
  ListReadingTextsParams,
  Grade,
  EducationStage,
  GuidedSession,
  GuidedSessionAnswer,
  CreateGuidedSessionPayload,
  ListGuidedSessionsParams,
  ApiErrorBody,
  ReadingSessionStatus,
  FluencyPartPayload,
  SaveFluencyPayload,
  SaveComprehensionAnswerItem,
  SaveComprehensionAnswersPayload,
  ReadingComprehensionAnswer,
  ReadingEvaluationSession,
  FluencyPartReport,
  FluencySessionReport,
  ReadingEvaluation,
  ReadingEvaluationStatus,
  ReadingAssessmentType,
  ListReadingEvaluationsParams,
} from "@/lib/api/afirme-reading/types";
